name: flutter_mvvm_template
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  hooks_riverpod: ^1.0.0
  flutter_hooks: ^0.18.0
  state_notifier: ^0.7.1

  dio: ^4.0.4
  retrofit: '>=3.0.0 <4.0.0'
  json_annotation: ^4.4.0

  freezed: ^1.0.0
  freezed_annotation: ^1.0.0

  webview_flutter:

  shared_preferences: ^2.0.8

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.4
  retrofit_generator: '>=3.0.0 <4.0.0'
  json_serializable: ^6.0.1

flutter:
  uses-material-design: true